export enum WhichAction {
  UPDATE_NAVBAR_PROFILE_PHOTO = 'UPDATE_NAVBAR_PROFILE_PHOTO',
  SHOW_ALERT_POPUP = 'SHOW_ALERT_POPUP',
  OPEN_MODAL = 'OPEN_MODAL',
  IS_MODAL_CONFIRMED = 'IS_MODAL_CONFIRMED',
}
